name: .NET Windows Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5

    - name: Get Version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      shell: bash

    - name: Update AssemblyInfo
      run: |
        $version = "${{ env.VERSION }}"
        $fileVersion = $version.Split('-')
        (Get-Content Properties\AssemblyInfo.cs) | ForEach-Object {
          $_ -replace '\[assembly: AssemblyVersion\(".*"\)\]', "[assembly: AssemblyVersion(""$fileVersion"")]" `
             -replace '\[assembly: AssemblyFileVersion\(".*"\)\]', "[assembly: AssemblyFileVersion(""$fileVersion"")]"
        } | Set-Content Properties\AssemblyInfo.cs
      shell: pwsh

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build and publish x64
      run: msbuild WinProxyEnvSync.csproj /p:Configuration=Release /p:Platform=x64 /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml
        
    - name: Build and publish x86
      run: msbuild WinProxyEnvSync.csproj /p:Configuration=Release /p:Platform=x86 /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml

    - name: Package Release
      run: |
        7z a -w bin/x64/Release WinProxyEnvSync-windows-x64-${{ env.VERSION }}.zip *
        7z a -w bin/x86/Release WinProxyEnvSync-windows-x86-${{ env.VERSION }}.zip *
      shell: cmd

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          WinProxyEnvSync-windows-x64-${{ env.VERSION }}.zip
          WinProxyEnvSync-windows-x86-${{ env.VERSION }}.zip